// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 2ad22dbd9cafd2d1a9ba05e890fd081f27fda2c20f4da06759d0d29de8a24a04

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "admin-with-direct-impersonation";

export const themeNames: ThemeName[] = ["admin-with-direct-impersonation"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./admin/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcAdminPage = lazy(() => import("./admin/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "admin":
                        return <KcAdminPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
